const patterns = [
    { value: 'CDL2CROWS', name: 'Two Crows', id: 1 },
    { value: 'CDL3BLACKCROWS', name: 'Three Black Crows', id: 2 },
    { value: 'CDL3INSIDE', name: 'Three Inside Up/Down', id: 3 },
    { value: 'CDL3LINESTRIKE', name: 'Three-Line Strike', id: 4 },
    { value: 'CDL3OUTSIDE', name: 'Three Outside Up/Down', id: 5 },
    { value: 'CDL3STARSINSOUTH', name: 'Three Stars In The South', id: 6 },
    { value: 'CDL3WHITESOLDIERS', name: 'Three Advancing White Soldiers', id: 7 },
    { value: 'CDLABANDONEDBABY', name: 'Abandoned Baby', id: 8 },
    { value: 'CDLADVANCEBLOCK', name: 'Advance Block', id: 9 },
    { value: 'CDLBELTHOLD', name: 'Belt-hold', id: 10 },
    { value: 'CDLBREAKAWAY', name: 'Breakaway', id: 11 },
    { value: 'CDLCLOSINGMARUBOZU', name: 'Closing Marubozu', id: 12 },
    { value: 'CDLCONCEALBABYSWALL', name: 'Concealing Baby Swallow', id: 13 },
    { value: 'CDLCOUNTERATTACK', name: 'Counterattack', id: 14 },
    { value: 'CDLDARKCLOUDCOVER', name: 'Dark Cloud Cover', id: 15 },
    { value: 'CDLDOJI', name: 'Doji', id: 16 },
    { value: 'CDLDOJISTAR', name: 'Doji Star', id: 17 },
    { value: 'CDLDRAGONFLYDOJI', name: 'Dragonfly Doji', id: 18 },
    { value: 'CDLENGULFING', name: 'Engulfing Pattern', id: 19 },
    { value: 'CDLEVENINGDOJISTAR', name: 'Evening Doji Star', id: 20 },
    { value: 'CDLEVENINGSTAR', name: 'Evening Star', id: 21 },
    { value: 'CDLGAPSIDESIDEWHITE', name: 'Up/Down-gap side-by-side white lines', id: 22 },
    { value: 'CDLGRAVESTONEDOJI', name: 'Gravestone Doji', id: 23 },
    { value: 'CDLHAMMER', name: 'Hammer', id: 24 },
    { value: 'CDLHANGINGMAN', name: 'Hanging Man', id: 25 },
    { value: 'CDLHARAMI', name: 'Harami Pattern', id: 26 },
    { value: 'CDLHARAMICROSS', name: 'Harami Cross Pattern', id: 27 },
    { value: 'CDLHIGHWAVE', name: 'High-Wave Candle', id: 28 },
    { value: 'CDLHIKKAKE', name: 'Hikkake Pattern', id: 29 },
    { value: 'CDLHIKKAKEMOD', name: 'Modified Hikkake Pattern', id: 30 },
    { value: 'CDLHOMINGPIGEON', name: 'Homing Pigeon', id: 31 },
    { value: 'CDLIDENTICAL3CROWS', name: 'Identical Three Crows', id: 32 },
    { value: 'CDLINNECK', name: 'In-Neck Pattern', id: 33 },
    { value: 'CDLINVERTEDHAMMER', name: 'Inverted Hammer', id: 34 },
    { value: 'CDLKICKING', name: 'Kicking', id: 35 },
    { value: 'CDLKICKINGBYLENGTH', name: 'Kicking - bull/bear determined by the longer marubozu', id: 36 },
    { value: 'CDLLADDERBOTTOM', name: 'Ladder Bottom', id: 37 },
    { value: 'CDLLONGLEGGEDDOJI', name: 'Long Legged Doji', id: 38 },
    { value: 'CDLLONGLINE', name: 'Long Line Candle', id: 39 },
    { value: 'CDLMARUBOZU', name: 'Marubozu', id: 40 },
    { value: 'CDLMATCHINGLOW', name: 'Matching Low', id: 41 },
    { value: 'CDLMATHOLD', name: 'Mat Hold', id: 42 },
    { value: 'CDLMORNINGDOJISTAR', name: 'Morning Doji Star', id: 43 },
    { value: 'CDLMORNINGSTAR', name: 'Morning Star', id: 44 },
    { value: 'CDLONNECK', name: 'On-Neck Pattern', id: 45 },
    { value: 'CDLPIERCING', name: 'Piercing Pattern', id: 46 },
    { value: 'CDLRICKSHAWMAN', name: 'Rickshaw Man', id: 47 },
    { value: 'CDLRISEFALL3METHODS', name: 'Rising/Falling Three Methods', id: 48 },
    { value: 'CDLSEPARATINGLINES', name: 'Separating Lines', id: 49 },
    { value: 'CDLSHOOTINGSTAR', name: 'Shooting Star', id: 50 },
    { value: 'CDLSHORTLINE', name: 'Short Line Candle', id: 51 },
    { value: 'CDLSPINNINGTOP', name: 'Spinning Top', id: 52 },
    { value: 'CDLSTALLEDPATTERN', name: 'Stalled Pattern', id: 53 },
    { value: 'CDLSTICKSANDWICH', name: 'Stick Sandwich', id: 54 },
    { value: 'CDLTAKURI', name: 'Takuri (Dragonfly Doji with very long lower shadow)', id: 55 },
    { value: 'CDLTASUKIGAP', name: 'Tasuki Gap', id: 56 },
    { value: 'CDLTHRUSTING', name: 'Thrusting Pattern', id: 57 },
    { value: 'CDLTRISTAR', name: 'Tristar Pattern', id: 58 },
    { value: 'CDLUNIQUE3RIVER', name: 'Unique 3 River', id: 59 },
    { value: 'CDLUPSIDEGAP2CROWS', name: 'Upside Gap Two Crows', id: 60 },
    { value: 'CDLXSIDEGAP3METHODS', name: 'Upside/Downside Gap Three Methods', id: 61 }
];

export default patterns;
